//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcApplication8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Institucion
    {
        public string CCT { get; set; }
        public string nombre { get; set; }
        public string grado { get; set; }
        public string municipio { get; set; }
        public string estado { get; set; }
        public string direccion { get; set; }
        public Nullable<int> telefono { get; set; }
    
    }
}
